// Generated by https://quicktype.io
using System;
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace SirSuperGeek.AzFunc.ShortUrl.Prismic
{

    public partial class ResultsResponse
    {
        [JsonProperty("page")]
        public long Page { get; set; }

        [JsonProperty("results_per_page")]
        public long ResultsPerPage { get; set; }

        [JsonProperty("results_size")]
        public long ResultsSize { get; set; }

        [JsonProperty("total_results_size")]
        public long TotalResultsSize { get; set; }

        [JsonProperty("total_pages")]
        public long TotalPages { get; set; }

        [JsonProperty("next_page")]
        public object NextPage { get; set; }

        [JsonProperty("prev_page")]
        public object PrevPage { get; set; }

        [JsonProperty("results")]
        public Result[] ResultsResults { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("license")]
        public string License { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("uid")]
        public object Uid { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("tags")]
        public object[] Tags { get; set; }

        [JsonProperty("first_publication_date")]
        public string FirstPublicationDate { get; set; }

        [JsonProperty("last_publication_date")]
        public string LastPublicationDate { get; set; }

        [JsonProperty("slugs")]
        public string[] Slugs { get; set; }

        [JsonProperty("linked_documents")]
        public object[] LinkedDocuments { get; set; }

        [JsonProperty("lang")]
        public string Lang { get; set; }

        [JsonProperty("alternate_languages")]
        public object[] AlternateLanguages { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("url")]
        public Url Url { get; set; }
    }

    public partial class Url
    {
        [JsonProperty("link_type")]
        public string LinkType { get; set; }

        [JsonProperty("url")]
        public Uri UrlUrl { get; set; }
    }

    public partial class Results
    {
        public static Results FromJson(string json) => JsonConvert.DeserializeObject<Results>(json, Prismic.Converter.Settings);
    }
    
}
